# Generated by Django 3.2.5 on 2021-08-04 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_code'),
        ('api', '0003_room_current_song'),
    ]

    operations = [
    ]
